title: Vertex snap in Unity
hero_image: images/banner.png
description: Use vertext snapping in Unity to align objects
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Vertex snap in Unity